icons_format = "{icon}"

[theme]
theme = "slick"
[theme.overrides]
idle_bg = "#2f343f"
idle_fg = "#f3f4f5"

[icons]
icons = "awesome4"
#[icons.overrides]
#bat = " | | "
#bat_full = " |X| "
#bat_charging = " |^| "
#bat_discharging = " |v| "

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol-qt"

[[block]]
block = "time"
interval = 5
#format = " $timestamp.datetime(f:'%a %d/%m %R') "
format = " $timestamp.datetime(f:'%a %Y-%m-%d %H:%M:%S') "

[[block]]
block = "battery"
format = " $icon $percentage {$time |}"

