icons_format = "{icon}"

[theme]
theme = "slick"
[theme.overrides]
idle_bg = "#2f343f"
idle_fg = "#f3f4f5"

[icons]
icons = "awesome4"
#[icons.overrides]
#bat = " | | "
#bat_full = " |X| "
#bat_charging = " |^| "
#bat_discharging = " |v| "

[[block]]
block = "net"
format = " $icon  {$signal_strength $ip $ssid$frequency ^icon_net_down$speed_down.eng(prefix:K) ^icon_net_up$speed_up.eng(prefix:K)|Wired connection} via $device "
[[block.click]]
button = "left"
cmd = "wezterm start nmtui"

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
#format = " $timestamp.datetime(f:'%a %d/%m %R') "
format = " $timestamp.datetime(f:'%a %Y-%m-%d %H:%M:%S') "

[[block]]
block = "backlight"
format = " $brightness "

[[block]]
block = "custom"
command = "if pgrep svkbd-mobile-in >/dev/null; then echo \"󰌌\"; else echo \"󰌐\"; fi"
interval = "once"
[[block.click]]
button = "left"
cmd = "if pgrep svkbd-mobile-in >/dev/null; then pkill svkbd-mobile-in; else svkbd-mobile-intl -d; fi"
update = true

[[block]]
block = "battery"
format = " $icon  $percentage {$time |}"
missing_format = ""
